### PR TITLE
Adds an AutoWayfinder component to help lost users

### PR DESCRIPTION
**Pull request by andrewmunroe**
Here's a map thing which will be accessible from the Help menu (at a cost of saltines). All you'd need to do is assign lat/long props to center the map and display a little marker. A couple questions:

1. Is it okay to use the same interface for PlaceMarker and AutoWayfinder?
2. I generated an API key using the AME! Google account. Is this okay to put on GitHub? Or how do you usually handle that?

### CODE REVIEW

**Comment by andrewmunroe** [comment]
Okay I added you.

**Comment by andrewmunroe** [comment]
@bradenmacdonald The latest commit adds the option to render a map on the scenario details screen. Would the simplest approach be to add new columns in the database to get `selectedScenario.start_point_lat` and `selectedScenario.start_point_lng`?

**Comment by andrewmunroe** [comment]
Added in a new optional prop `lost` that will render a different type of marker if we're showing a 'lost user' vs. 'starting point' map. The other main difference is that the 'lost' map can't be zoomed in to make it a bit more challenging.

**Comment by bradenmacdonald** [comment]
Closing in favor of #14.

**Pull request closed without merging**
